### ISSUE TITLE
update to latest bidict?

### ISSUE THREAD

**Issue by jab** [pexip/os-python-bidict#1]
Dear @jmb202,

I am the author of bidict and just came across this repo. Not exactly sure what it is but just wanted to let you know there is a more recent and much-improved release of bidict available since the one packaged here. Always interested to hear about your experience, use cases, and any other feedback about bidict.

Thanks,
–jab

**Comment by jmb202** [comment]
Thanks. This repository contains packaging for our OS. We're currently have no need to upgrade, as the version we are using is working fine for our needs!

**Comment by jab** [comment]
Fair enough! Hope you reconsider though as the latest version has bugfixes, performance, and other improvements.
